name: publish
on:
  push:
    branches: [ "development" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_DIR: /var/www/insync


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSYNC_DEV_SSH_SERVER }}
          username: ${{ secrets.INSYNC_DEV_SSH_USER }}
          key: ${{ secrets.INSYNC_DEV_SSH_KEY }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_REPOSITORY,DEPLOY_DIR
          script: |
            [ -d "$HOME/$GITHUB_REPOSITORY" ] && rm -rf "$HOME/$GITHUB_REPOSITORY"
            mkdir -p "$HOME/$GITHUB_REPOSITORY"
            git clone https://github.com/$GITHUB_REPOSITORY "$HOME/$GITHUB_REPOSITORY"
            cd "$HOME/$GITHUB_REPOSITORY"
            export NODE_OPTIONS=--openssl-legacy-provider
            [ -f "./package-lock.json" ] && rm package-lock.json
            git stash &&
              git checkout development &&
              git pull origin development &&
              yarn &&
              yarn build &&
              mkdir -p /var/www/html/ &&
              sudo rm -rf /var/www/html/insync-development/ &&
              sudo mv "${PROJECT_DIR}"/build/ /var/www/html/insync-development
