name: Deploy

on:
  push:
    branches: [ "development" ]

  workflow_dispatch:
jobs:
  lint_test:
    runs-on: ubuntu-latest
    container: node:15-alpine
    steps:
      - name: Lint Test
        run: |    
          apk add g++ make python
          yarn
          $(pwd)/node_modules/.bin/eslint $(pwd)
